// Nextjs
import Head from 'next/head'
// Context
import { AppContextProvider } from './context/AppContext'
// Styles
import './globals.css'

export const metadata = {
	title: 'Pal Patio Export',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<AppContextProvider>
			<html lang="es">
				<head>
					<link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.4.0/css/all.css" />
					<link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.4.0/css/sharp-light.css" />
				</head>
				<body>{children}</body>
			</html>
		</AppContextProvider>
	)
}