// Layout
import Layout from "./components/Layout"
// Sections
import HeroSection from "./components/Home/Hero/Index"
import QuoteOrder from "./components/Home/QuoteOrder/Index"
import WhatSend from "./components/Home/WhatSend/Index"
import FeaturedFeatures from "./components/Home/FeaturedFeatures/Index"
import Process from "./components/Home/Process/Index"
import AboutUs from "./components/Home/AboutUs/Index"
import FAQ from "./components/Home/FAQ/Index"
// Styles
import styles from './page.module.css'

export const metadata = {
	title: 'Inicio | Pal Patio Export',
	description: 'Generated by create next app',
}

export default function Home() {

	return (
		<Layout>
			<HeroSection />
			<div className={styles.container}>
				<QuoteOrder />
				<WhatSend />
			</div>
			<div className={"divide-y"}>
				<FeaturedFeatures />
				<Process />
			</div>
			<AboutUs />
			<FAQ />
		</Layout>
	)
}